### PR TITLE
[4098777844] Feature/animation extractor update

### PR DESCRIPTION
**Pull request by HarrisonHough**
## Description

- animation extractor now works with multiple files (if you have multiple fbx files selected when you do it) 

#### Added

-   support for extracting animations from multiple .fbx files at once

#### Updated

-   refactor and cleanup of AnimationExtractor

## How to Test

-   Add steps to locally test these changes

## Checklist

-   [ ] Tests written or updated for the changes.
-   [ ] Documentation is updated.
-   [ ] Changelog is updated.
-   [ ] QA Testing is updated.

## QA Testing

-   Mention any useful test cases for this feature and add to QA Testing documentation.

## Details

image

### CODE REVIEW

**Comment by srcnalt** [comment]
I downloaded 2 FBX files from mixamo, where both had animation files called `mixamo.com` extract and delete resulted in single anim file. Must be due to name collision. Can you check that?

**Comment by HarrisonHough** [comment]
> I downloaded 2 FBX files from mixamo, where both had animation files called `mixamo.com` extract and delete resulted in single anim file. Must be due to name collision. Can you check that?

why you have to find edge cases!!  -____________-

**Comment by HarrisonHough** [comment]
> ## [4098777844](https://ready-player-me.monday.com/boards/2563815861/pulses/4098777844)
> ## Description
> 
>     * animation extractor now works with multiple files (if you have multiple fbx files selected when you do it)
> 
> 
> ## Changes
> #### Added
> 
>     * support for extracting animations from multiple .fbx files at once
> 
> 
> #### Updated
> 
>     * refactor and cleanup of AnimationExtractor
> 
> 
> ## How to Test
> 
>     * Add steps to locally test these changes
> 
> 
> ## Checklist
> 
>     * [ ]  Tests written or updated for the changes.
> 
>     * [ ]  Documentation is updated.
> 
>     * [ ]  Changelog is updated.
> 
>     * [ ]  QA Testing is updated.
> 
> 
> ## QA Testing
> 
>     * Mention any useful test cases for this feature and add to QA Testing documentation.
> 
> 
> ## Details
> 
> image

should be fixed now

**Comment by HarrisonHough** [comment]
> ## [4098777844](https://ready-player-me.monday.com/boards/2563815861/pulses/4098777844)
> ## Description
> 
>     * animation extractor now works with multiple files (if you have multiple fbx files selected when you do it)
> 
> 
> ## Changes
> #### Added
> 
>     * support for extracting animations from multiple .fbx files at once
> 
> 
> #### Updated
> 
>     * refactor and cleanup of AnimationExtractor
> 
> 
> ## How to Test
> 
>     * Add steps to locally test these changes
> 
> 
> ## Checklist
> 
>     * [ ]  Tests written or updated for the changes.
> 
>     * [ ]  Documentation is updated.
> 
>     * [ ]  Changelog is updated.
> 
>     * [ ]  QA Testing is updated.
> 
> 
> ## QA Testing
> 
>     * Mention any useful test cases for this feature and add to QA Testing documentation.
> 
> 
> ## Details
> 
> image

should be fixed now

**Pull request merged**
