### PR TITLE
[SDK-187] Add avatar config inspector using UI toolkit

### PR DESCRIPTION
**Pull request by rYuuk**
## Dependencies
```Package
Core: develop
```
#### Added

-  Avatar config inspector using UI Toolkit

## How to Test

- Check avatar config scriptable object, change values and observe if those change persist. 
- Also load avatar by using them in runtime and editor.

## Checklist

-   [ ] Tests written or updated for the changes.
-   [ ] Documentation is updated.
-   [ ] Changelog is updated.

[SDK-187]: https://ready-player-me.atlassian.net/browse/SDK-187?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by HarrisonHough — CHANGES_REQUESTED** [review]
I tried testing/opening the branch and I got some errors, is it the same for you? 

image

image

**Comment by rYuuk** [comment]
@HarrisonHough Fixed, you can try again.

**Review by HarrisonHough — APPROVED** [review]
All seems to work. 
One minor issue that happens quite often when trying to select a blendshape in the morphtargets is an OutOfRange exception error. 
Doesn't particularly break anything though mostly just annoying. 
image

**Comment by rYuuk** [comment]
@HarrisonHough Thanks for finding this. It turned out to be a critical error, which could have broken stuff.

**Pull request merged**
